### ISSUE TITLE
yarn build-server 报错 : Cannot find module 

### ISSUE THREAD

**Issue by happyworker101** [S-mohan/koa-webpack-typescript#1]
我把项目clone到本地 安装依赖包后 执行yarn build-server， 控制台报错
![image](https://user-images.githubusercontent.com/32256182/64502135-f7a3b680-d2f6-11e9-8594-c4f94c174a10.png)
这是什么情况呢？怎么解决呢？

**Comment by S-mohan** [comment]
npm i koa
